import { Profanity } from '~/types'

// How to convert text file to string[]
// https://techstacker.com/vscode-insert-cursor-beginning-every-line/
// 1. Cmd + A - select all lines
// 2. Option + Shift + I - insert cursor at the end of every line
// 3. Hold down the Fn button + left arrow key - insert cursor at beginning of every line
// 4. Cmd + A - get out of cursor mode
// copied from https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
const profanities: Profanity[] = [
  { word: '2g1c', level: 'mild' },
  { word: '2 girls 1 cup', level: 'mild' },
  { word: 'acrotomophilia', level: 'mild' },
  { word: 'alabama hot pocket', level: 'mild' },
  { word: 'alaskan pipeline', level: 'mild' },
  { word: 'anal', level: 'strong' },
  { word: 'anilingus', level: 'medium' },
  { word: 'anus', level: 'medium' },
  { word: 'apeshit', level: 'strong' },
  { word: 'arsehole', level: 'mild' },
  { word: 'ass', level: 'medium' },
  { word: 'asshole', level: 'strong' },
  { word: 'assmunch', level: 'mild' },
  { word: 'auto erotic', level: 'mild' },
  { word: 'autoerotic', level: 'mild' },
  { word: 'babeland', level: 'mild' },
  { word: 'baby batter', level: 'medium' },
  { word: 'baby juice', level: 'medium' },
  { word: 'ball gag', level: 'strong' },
  { word: 'ball gravy', level: 'strong' },
  { word: 'ball kicking', level: 'strong' },
  { word: 'ball licking', level: 'strongest' },
  { word: 'ball sack', level: 'strongest' },
  { word: 'ball sucking', level: 'strongest' },
  { word: 'bangbros', level: 'strongest' },
  { word: 'bangbus', level: 'strongest' },
  { word: 'bareback', level: 'strong' },
  { word: 'barely legal', level: 'mild' },
  { word: 'barenaked', level: 'strong' },
  { word: 'bastard', level: 'strongest' },
  { word: 'bastardo', level: 'strongest' },
  { word: 'bastinado', level: 'strongest' },
  { word: 'bbw', level: 'mild' },
  { word: 'bdsm', level: 'medium' },
  { word: 'beaner', level: 'strongest' },
  { word: 'beaners', level: 'strongest' },
  { word: 'beaver cleaver', level: 'strong' },
  { word: 'beaver lips', level: 'mild' },
  { word: 'beastiality', level: 'medium' },
  { word: 'bestiality', level: 'mild' },
  { word: 'big black', level: 'mild' },
  { word: 'big breasts', level: 'strong' },
  { word: 'big knockers', level: 'strongest' },
  { word: 'big tits', level: 'strongest' },
  { word: 'bimbos', level: 'strongest' },
  { word: 'birdlock', level: 'mild' },
  { word: 'bitch', level: 'strongest' },
  { word: 'bitches', level: 'strongest' },
  { word: 'black cock', level: 'strongest' },
  { word: 'blonde action', level: 'strong' },
  { word: 'blonde on blonde action', level: 'medium' },
  { word: 'blowjob', level: 'strongest' },
  { word: 'blow job', level: 'strongest' },
  { word: 'blow your load', level: 'strongest' },
  { word: 'blue waffle', level: 'medium' },
  { word: 'blumpkin', level: 'medium' },
  { word: 'bollocks', level: 'mild' },
  { word: 'bondage', level: 'strong' },
  { word: 'boner', level: 'strong' },
  { word: 'boob', level: 'mild' },
  { word: 'boobs', level: 'medium' },
  { word: 'booty call', level: 'mild' },
  { word: 'brown showers', level: 'mild' },
  { word: 'brunette action', level: 'mild' },
  { word: 'bukkake', level: 'strongest' },
  { word: 'bulldyke', level: 'strong' },
  { word: 'bullet vibe', level: 'mild' },
  { word: 'bullshit', level: 'strongest' },
  { word: 'bung hole', level: 'strong' },
  { word: 'bunghole', level: 'medium' },
  { word: 'busty', level: 'medium' },
  { word: 'butt', level: 'mild' },
  { word: 'buttcheeks', level: 'mild' },
  { word: 'butthole', level: 'mild' },
  { word: 'camel toe', level: 'strong' },
  { word: 'camgirl', level: 'medium' },
  { word: 'camslut', level: 'strongest' },
  { word: 'camwhore', level: 'strongest' },
  { word: 'carpet muncher', level: 'medium' },
  { word: 'carpetmuncher', level: 'medium' },
  { word: 'chocolate rosebuds', level: 'medium' },
  { word: 'cialis', level: 'mild' },
  { word: 'circlejerk', level: 'mild' },
  { word: 'cleveland steamer', level: 'medium' },
  { word: 'clit', level: 'strongest' },
  { word: 'clitoris', level: 'mild' },
  { word: 'clover clamps', level: 'medium' },
  { word: 'clusterfuck', level: 'strongest' },
  { word: 'cock', level: 'strongest' },
  { word: 'cocks', level: 'strongest' },
  { word: 'coprolagnia', level: 'mild' },
  { word: 'coprophilia', level: 'mild' },
  { word: 'cornhole', level: 'mild' },
  { word: 'coon', level: 'strongest' },
  { word: 'coons', level: 'strongest' },
  { word: 'creampie', level: 'strong' },
  { word: 'cum', level: 'strong' },
  { word: 'cumming', level: 'strong' },
  { word: 'cumshot', level: 'strong' },
  { word: 'cumshots', level: 'strong' },
  { word: 'cunnilingus', level: 'mild' },
  { word: 'cunt', level: 'strongest' },
  { word: 'darkie', level: 'strongest' },
  { word: 'date rape', level: 'strong' },
  { word: 'daterape', level: 'strong' },
  { word: 'deep throat', level: 'strongest' },
  { word: 'deepthroat', level: 'strongest' },
  { word: 'dendrophilia', level: 'mild' },
  { word: 'dick', level: 'strongest' },
  { word: 'dildo', level: 'medium' },
  { word: 'dingleberry', level: 'medium' },
  { word: 'dingleberries', level: 'medium' },
  { word: 'dirty pillows', level: 'medium' },
  { word: 'dirty sanchez', level: 'medium' },
  { word: 'doggie style', level: 'strong' },
  { word: 'doggiestyle', level: 'strong' },
  { word: 'doggy style', level: 'strong' },
  { word: 'doggystyle', level: 'strong' },
  { word: 'dog style', level: 'strong' },
  { word: 'dolcett', level: 'mild' },
  { word: 'domination', level: 'mild' },
  { word: 'dominatrix', level: 'mild' },
  { word: 'dommes', level: 'mild' },
  { word: 'donkey punch', level: 'mild' },
  { word: 'double dong', level: 'strong' },
  { word: 'double penetration', level: 'strong' },
  { word: 'dp action', level: 'strong' },
  { word: 'dry hump', level: 'medium' },
  { word: 'dvda', level: 'mild' },
  { word: 'eat my ass', level: 'medium' },
  { word: 'ecchi', level: 'medium' },
  { word: 'ejaculation', level: 'mild' },
  { word: 'erotic', level: 'mild' },
  { word: 'erotism', level: 'mild' },
  { word: 'escort', level: 'mild' },
  { word: 'eunuch', level: 'mild' },
  { word: 'fag', level: 'strongest' },
  { word: 'faggot', level: 'strongest' },
  { word: 'fecal', level: 'mild' },
  { word: 'felch', level: 'mild' },
  { word: 'fellatio', level: 'medium' },
  { word: 'feltch', level: 'mild' },
  { word: 'female squirting', level: 'strong' },
  { word: 'femdom', level: 'mild' },
  { word: 'figging', level: 'mild' },
  { word: 'fingerbang', level: 'strong' },
  { word: 'fingering', level: 'strong' },
  { word: 'fisting', level: 'strong' },
  { word: 'foot fetish', level: 'medium' },
  { word: 'footjob', level: 'strong' },
  { word: 'frotting', level: 'mild' },
  { word: 'fuck', level: 'strongest' },
  { word: 'fuck buttons', level: 'strongest' },
  { word: 'fuckin', level: 'strongest' },
  { word: 'fucking', level: 'strongest' },
  { word: 'fucktards', level: 'strongest' },
  { word: 'fudge packer', level: 'mild' },
  { word: 'fudgepacker', level: 'mild' },
  { word: 'futanari', level: 'mild' },
  { word: 'gangbang', level: 'strong' },
  { word: 'gang bang', level: 'strong' },
  { word: 'gay sex', level: 'mild' },
  { word: 'genitals', level: 'mild' },
  { word: 'giant cock', level: 'strongest' },
  { word: 'girl on', level: 'mild' },
  { word: 'girl on top', level: 'mild' },
  { word: 'girls gone wild', level: 'mild' },
  { word: 'goatcx', level: 'mild' },
  { word: 'goatse', level: 'mild' },
  { word: 'god damn', level: 'medium' },
  { word: 'gokkun', level: 'mild' },
  { word: 'golden shower', level: 'medium' },
  { word: 'goodpoop', level: 'mild' },
  { word: 'goo girl', level: 'mild' },
  { word: 'goregasm', level: 'medium' },
  { word: 'grope', level: 'mild' },
  { word: 'group sex', level: 'medium' },
  { word: 'g-spot', level: 'medium' },
  { word: 'guro', level: 'mild' },
  { word: 'hand job', level: 'strong' },
  { word: 'handjob', level: 'strong' },
  { word: 'hard core', level: 'mild' },
  { word: 'hardcore', level: 'mild' },
  { word: 'hentai', level: 'mild' },
  { word: 'homoerotic', level: 'mild' },
  { word: 'honkey', level: 'mild' },
  { word: 'hooker', level: 'medium' },
  { word: 'horny', level: 'medium' },
  { word: 'hot carl', level: 'mild' },
  { word: 'hot chick', level: 'mild' },
  { word: 'how to kill', level: 'strongest' },
  { word: 'how to murder', level: 'strongest' },
  { word: 'huge fat', level: 'mild' },
  { word: 'humping', level: 'mild' },
  { word: 'incest', level: 'strong' },
  { word: 'intercourse', level: 'mild' },
  { word: 'jack off', level: 'strong' },
  { word: 'jail bait', level: 'strong' },
  { word: 'jailbait', level: 'strong' },
  { word: 'jelly donut', level: 'mild' },
  { word: 'jerk off', level: 'strong' },
  { word: 'jigaboo', level: 'strongest' },
  { word: 'jiggaboo', level: 'strongest' },
  { word: 'jiggerboo', level: 'strongest' },
  { word: 'jizz', level: 'medium' },
  { word: 'juggs', level: 'strongest' },
  { word: 'kike', level: 'strongest' },
  { word: 'kinbaku', level: 'mild' },
  { word: 'kinkster', level: 'mild' },
  { word: 'kinky', level: 'mild' },
  { word: 'knobbing', level: 'mild' },
  { word: 'leather restraint', level: 'mild' },
  { word: 'leather straight jacket', level: 'mild' },
  { word: 'lemon party', level: 'mild' },
  { word: 'livesex', level: 'mild' },
  { word: 'lolita', level: 'medium' },
  { word: 'lovemaking', level: 'mild' },
  { word: 'make me come', level: 'strong' },
  { word: 'male squirting', level: 'strong' },
  { word: 'masturbate', level: 'mild' },
  { word: 'masturbating', level: 'mild' },
  { word: 'masturbation', level: 'mild' },
  { word: 'menage a trois', level: 'mild' },
  { word: 'milf', level: 'mild' },
  { word: 'missionary position', level: 'mild' },
  { word: 'mong', level: 'strongest' },
  { word: 'motherfucker', level: 'strongest' },
  { word: 'mound of venus', level: 'mild' },
  { word: 'mr hands', level: 'mild' },
  { word: 'muff diver', level: 'medium' },
  { word: 'muffdiving', level: 'medium' },
  { word: 'nambla', level: 'mild' },
  { word: 'nawashi', level: 'mild' },
  { word: 'negro', level: 'strongest' },
  { word: 'neonazi', level: 'mild' },
  { word: 'nigga', level: 'strongest' },
  { word: 'nigger', level: 'strongest' },
  { word: 'nig nog', level: 'strongest' },
  { word: 'nimphomania', level: 'mild' },
  { word: 'nipple', level: 'mild' },
  { word: 'nipples', level: 'mild' },
  { word: 'nsfw', level: 'mild' },
  { word: 'nsfw images', level: 'mild' },
  { word: 'nude', level: 'mild' },
  { word: 'nudity', level: 'mild' },
  { word: 'nutten', level: 'mild' },
  { word: 'nympho', level: 'mild' },
  { word: 'nymphomania', level: 'mild' },
  { word: 'octopussy', level: 'medium' },
  { word: 'omorashi', level: 'mild' },
  { word: 'one cup two girls', level: 'mild' },
  { word: 'one guy one jar', level: 'mild' },
  { word: 'orgasm', level: 'mild' },
  { word: 'orgy', level: 'mild' },
  { word: 'paedophile', level: 'mild' },
  { word: 'paki', level: 'mild' },
  { word: 'panties', level: 'mild' },
  { word: 'panty', level: 'mild' },
  { word: 'pedobear', level: 'strong' },
  { word: 'pedophile', level: 'mild' },
  { word: 'pegging', level: 'medium' },
  { word: 'penis', level: 'mild' },
  { word: 'phone sex', level: 'mild' },
  { word: 'piece of shit', level: 'strongest' },
  { word: 'pikey', level: 'strongest' },
  { word: 'pissing', level: 'medium' },
  { word: 'piss pig', level: 'strong' },
  { word: 'pisspig', level: 'strong' },
  { word: 'playboy', level: 'mild' },
  { word: 'pleasure chest', level: 'strong' },
  { word: 'pole smoker', level: 'mild' },
  { word: 'ponyplay', level: 'mild' },
  { word: 'poof', level: 'mild' },
  { word: 'poon', level: 'medium' },
  { word: 'poontang', level: 'medium' },
  { word: 'punany', level: 'medium' },
  { word: 'poop chute', level: 'mild' },
  { word: 'poopchute', level: 'mild' },
  { word: 'porn', level: 'mild' },
  { word: 'porno', level: 'mild' },
  { word: 'pornography', level: 'mild' },
  { word: 'prince albert piercing', level: 'mild' },
  { word: 'pthc', level: 'mild' },
  { word: 'pubes', level: 'strong' },
  { word: 'pussy', level: 'strongest' },
  { word: 'queaf', level: 'strongest' },
  { word: 'queef', level: 'strongest' },
  { word: 'quim', level: 'strongest' },
  { word: 'raghead', level: 'strongest' },
  { word: 'raging boner', level: 'medium' },
  { word: 'rape', level: 'strongest' },
  { word: 'raping', level: 'strongest' },
  { word: 'rapist', level: 'strongest' },
  { word: 'rectum', level: 'medium' },
  { word: 'reverse cowgirl', level: 'medium' },
  { word: 'rimjob', level: 'strongest' },
  { word: 'rimming', level: 'strongest' },
  { word: 'rosy palm', level: 'mild' },
  { word: 'rosy palm and her 5 sisters', level: 'mild' },
  { word: 'rusty trombone', level: 'mild' },
  { word: 'sadism', level: 'mild' },
  { word: 'santorum', level: 'mild' },
  { word: 'scat', level: 'mild' },
  { word: 'schlong', level: 'strong' },
  { word: 'scissoring', level: 'strong' },
  { word: 'semen', level: 'mild' },
  { word: 'sex', level: 'mild' },
  { word: 'sexcam', level: 'mild' },
  { word: 'sexo', level: 'medium' },
  { word: 'sexy', level: 'medium' },
  { word: 'sexual', level: 'mild' },
  { word: 'sexually', level: 'mild' },
  { word: 'sexuality', level: 'mild' },
  { word: 'shaved beaver', level: 'strong' },
  { word: 'shaved pussy', level: 'strongest' },
  { word: 'shemale', level: 'mild' },
  { word: 'shibari', level: 'mild' },
  { word: 'shit', level: 'strongest' },
  { word: 'shitblimp', level: 'strongest' },
  { word: 'shitty', level: 'strongest' },
  { word: 'shota', level: 'medium' },
  { word: 'shrimping', level: 'medium' },
  { word: 'skeet', level: 'medium' },
  { word: 'slanteye', level: 'strongest' },
  { word: 'slut', level: 'strongest' },
  { word: 's&m', level: 'mild' },
  { word: 'smut', level: 'medium' },
  { word: 'snatch', level: 'mild' },
  { word: 'snowballing', level: 'mild' },
  { word: 'sodomize', level: 'mild' },
  { word: 'sodomy', level: 'mild' },
  { word: 'spastic', level: 'mild' },
  { word: 'spic', level: 'strongest' },
  { word: 'splooge', level: 'medium' },
  { word: 'splooge moose', level: 'medium' },
  { word: 'spooge', level: 'medium' },
  { word: 'spread legs', level: 'strong' },
  { word: 'spunk', level: 'strong' },
  { word: 'strap on', level: 'medium' },
  { word: 'strapon', level: 'medium' },
  { word: 'strappado', level: 'medium' },
  { word: 'strip club', level: 'mild' },
  { word: 'style doggy', level: 'strong' },
  { word: 'suck', level: 'mild' },
  { word: 'sucks', level: 'mild' },
  { word: 'suicide girls', level: 'strong' },
  { word: 'sultry women', level: 'strongest' },
  { word: 'swastika', level: 'mild' },
  { word: 'swinger', level: 'mild' },
  { word: 'tainted love', level: 'medium' },
  { word: 'taste my', level: 'medium' },
  { word: 'tea bagging', level: 'medium' },
  { word: 'threesome', level: 'mild' },
  { word: 'throating', level: 'strong' },
  { word: 'thumbzilla', level: 'medium' },
  { word: 'tied up', level: 'medium' },
  { word: 'tight white', level: 'medium' },
  { word: 'tit', level: 'strong' },
  { word: 'tits', level: 'strong' },
  { word: 'titties', level: 'strong' },
  { word: 'titty', level: 'strong' },
  { word: 'tongue in a', level: 'mild' },
  { word: 'topless', level: 'mild' },
  { word: 'tosser', level: 'mild' },
  { word: 'towelhead', level: 'mild' },
  { word: 'tranny', level: 'mild' },
  { word: 'tribadism', level: 'mild' },
  { word: 'tub girl', level: 'mild' },
  { word: 'tubgirl', level: 'mild' },
  { word: 'tushy', level: 'mild' },
  { word: 'twat', level: 'strong' },
  { word: 'twink', level: 'strongest' },
  { word: 'twinkie', level: 'strongest' },
  { word: 'two girls one cup', level: 'medium' },
  { word: 'undressing', level: 'mild' },
  { word: 'upskirt', level: 'medium' },
  { word: 'urethra play', level: 'medium' },
  { word: 'urophilia', level: 'medium' },
  { word: 'vagina', level: 'mild' },
  { word: 'venus mound', level: 'medium' },
  { word: 'viagra', level: 'mild' },
  { word: 'vibrator', level: 'mild' },
  { word: 'violet wand', level: 'mild' },
  { word: 'vorarephilia', level: 'mild' },
  { word: 'voyeur', level: 'mild' },
  { word: 'voyeurweb', level: 'mild' },
  { word: 'voyuer', level: 'mild' },
  { word: 'vulva', level: 'mild' },
  { word: 'wank', level: 'strong' },
  { word: 'wetback', level: 'strongest' },
  { word: 'wet dream', level: 'mild' },
  { word: 'white power', level: 'strongest' },
  { word: 'whore', level: 'strongest' },
  { word: 'worldsex', level: 'mild' },
  { word: 'wrapping men', level: 'mild' },
  { word: 'wrinkled starfish', level: 'mild' },
  { word: 'xx', level: 'mild' },
  { word: 'xxx', level: 'mild' },
  { word: 'yaoi', level: 'mild' },
  { word: 'yellow showers', level: 'medium' },
  { word: 'yiffy', level: 'strongest' },
  { word: 'zoophilia', level: 'mild' },
]

export default profanities
